name: bdd_isearch
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bdd_widget_test: ^1.6.0
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  mocked_backend: ^1.0.6

flutter:
  uses-material-design: true