name: bdd_isearch
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.0
  freezed_annotation: ^2.4.1
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.1
  injectable: ^2.1.2
  retrofit: ^4.0.1
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bdd_widget_test: ^1.6.0
  build_runner: ^2.3.3
  mocktail: ^0.3.0
  mocked_backend: ^1.0.6
  freezed: ^2.4.1
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true